# [START cloudbuild_quickstart_build]
steps:
  # -------------------- Build docker image from dockerfile in the root of the repo ---------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '--no-cache'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/note-app-vue/note-app-vue:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: 'build'

  # -------------------- Push to google repo ---------------------------------
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/note-app-vue/note-app-vue:$COMMIT_SHA'
    id: 'push'

  # -------------------- Deploy ---------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - note-app-vue
      - '--platform=managed'
      - '--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/note-app-vue/note-app-vue:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
    waitFor: ['push']
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/note-app-vue/note-app-vue:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - cookerii_backend
# [END cloudbuild_quickstart_build]